app = "repository-test-updated"

primary_region = "lhr"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "http"
  internal_port = 8080

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.http_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "20s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
