app = "repository-test-updated"

primary_region = "lhr"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
