app = "repository-test-updated"

primary_region = "lhr"

[env]
  PORT = "8080"
  WEB_CONCURRENCY = "1"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
