app = "repository-test-updated"
primary_region = "lhr"

[build]
dockerfile = "Dockerfile"

[env]
# Здесь твои переменные окружения
# TELEGRAM_TOKEN = "your_telegram_token"
# TELEGRAM_CHAT_ID = "your_chat_id"
# DEBUG_MODE = "True"
# USE_WEB3 = "true"
MIN_LIQ_USD = "5000"

[processes]
app = "python3 main.py"
