app = "repository-test"
region = "lhr"  # Лондон (London Heathrow)

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder:base"

[deploy]
  release_command = ""

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
